package com.PrixDeTransfert.Backend.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.PrixDeTransfert.Backend.models.InformationsSurContrepartieNonMonetairePourBiensOuServicesBD;

import jakarta.servlet.http.HttpSession;

@RestController
public class ControllerInformationsSurContrepartieNonMonetairePourBiensOuServices {
	@Autowired
	com.PrixDeTransfert.Backend.services.ServiceInformationsSurContrepartieNonMonetairePourBiensOuServices ServiceInformationsSurContrepartieNonMonetairePourBiensOuServices;
	
	@PostMapping("/DéclarationPrixDeTransfert/InformationsOperations/OperationsSansContrepartieOuAvecContrepartieNonMonetaire/InformationsSurContrepartieNonMonetairePourBiensOuServices")
	public InformationsSurContrepartieNonMonetairePourBiensOuServicesBD save(@RequestBody InformationsSurContrepartieNonMonetairePourBiensOuServicesBD  a,HttpSession session) {
		Long IdOperationsSansContrepartieOuAvecContrepartieNonMonetaire=(Long) session.getAttribute("IdOperationsSansContrepartieOuAvecContrepartieNonMonetaire");
		InformationsSurContrepartieNonMonetairePourBiensOuServicesBD InformationsSurContrepartieNonMonetairePourBiensOuServicesBD=ServiceInformationsSurContrepartieNonMonetairePourBiensOuServices.save(a, IdOperationsSansContrepartieOuAvecContrepartieNonMonetaire);
		session.setAttribute("idInformationsSurContrepartieNonMonetairePourBiensOuServices", InformationsSurContrepartieNonMonetairePourBiensOuServicesBD.getId());
		return InformationsSurContrepartieNonMonetairePourBiensOuServicesBD ;}

}
