package com.PrixDeTransfert.Backend.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.PrixDeTransfert.Backend.models.DéclarationPrixDeTransfert;
import com.PrixDeTransfert.Backend.models.InformationsCessionsAcquisitionsActifsBD;
import com.PrixDeTransfert.Backend.models.InformationsOperationsBD;
import com.PrixDeTransfert.Backend.models.InformationsOperationsFinancieresBD;
import com.PrixDeTransfert.Backend.models.MontantTransactionsMethodeDeterminationPrixTransfertBD;

import jakarta.servlet.http.HttpSession;

@RestController
public class ControllerInformationsCessionsAcquisitionsActifs {
	@Autowired
	private com.PrixDeTransfert.Backend.services.ServiceInformationsCessionsAcquisitionsActifs ServiceInformationsCessionsAcquisitionsActifs;
	
	@PostMapping("/DéclarationPrixDeTransfert/MontantTransaction/InformationsCessionsAcquisitionsActifs")// lid nekhdho m return mta InformationsValeursExploitation.save(a, idDéclaration)(khatr montantTransaction o informationsOperations yetsan3o mara kahw
	public InformationsCessionsAcquisitionsActifsBD save(@RequestBody InformationsCessionsAcquisitionsActifsBD  a,HttpSession session) {
		Long idMontantTransaction =(Long) session.getAttribute("idMontantTransactions");
		InformationsCessionsAcquisitionsActifsBD InformationsCessionsAcquisitionsActifsBD=ServiceInformationsCessionsAcquisitionsActifs.save(a, idMontantTransaction);
		session.setAttribute("idInformationsCessionsAcquisitionsActifs", InformationsCessionsAcquisitionsActifsBD.getId());
		return InformationsCessionsAcquisitionsActifsBD;}
	
	
	@Autowired
	com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryDéclarationPrixDeTransfert InterfaceRepositoryDéclarationPrixDeTransfert;
	@Autowired
    com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryInformationsCessionsAcquisitionsActifs InterfaceRepositoryInformationsCessionsAcquisitionsActifs;
	@PutMapping("/MiseAjourInformationsCessionsAcquisitionsActifs")
	public ResponseEntity<String> updateInformationsCessionsAcquisitionsActifs(@RequestBody InformationsCessionsAcquisitionsActifsBD updatedInformationsCessionsAcquisitionsActifs,HttpSession session) {
	
		Long iddeclaration =(Long) session.getAttribute("Déclarationid");
		DéclarationPrixDeTransfert DéclarationPrixDeTransfert =InterfaceRepositoryDéclarationPrixDeTransfert.findDéclarationPrixDeTransfertById(iddeclaration);
		InformationsOperationsBD InformationsOperations=DéclarationPrixDeTransfert.getInformationsOperations();
		MontantTransactionsMethodeDeterminationPrixTransfertBD MontantTransactionsMethodeDeterminationPrixTransfert=InformationsOperations.getMontantTransactionsMethodeDeterminationPrixTransfert();
		
		InformationsCessionsAcquisitionsActifsBD InformationsCessionsAcquisitionsActifs=MontantTransactionsMethodeDeterminationPrixTransfert.getInformationsCessionsAcquisitionsActifs();
	
	InformationsCessionsAcquisitionsActifs.setTotalAchatsDepensesCessionsAcquisitionsActifs(updatedInformationsCessionsAcquisitionsActifs.getTotalAchatsDepensesCessionsAcquisitionsActifs());
	InformationsCessionsAcquisitionsActifs.setTotalVentesRevenusCessionsAcquisitionsActifs(updatedInformationsCessionsAcquisitionsActifs.getTotalVentesRevenusCessionsAcquisitionsActifs());
	session.setAttribute("idInformationsCessionsAcquisitionsActifs", InformationsCessionsAcquisitionsActifs.getId());
	InterfaceRepositoryInformationsCessionsAcquisitionsActifs.save(InformationsCessionsAcquisitionsActifs);
	return ResponseEntity.ok(" mise à jour avec succès");}
	
}
