package com.PrixDeTransfert.Backend.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com.PrixDeTransfert.Backend.models.LigneContrepartieNonMonetairePourBiensOuServicesBD;



public interface InterfaceRepositoryLigneContrepartieNonMonetairePourBiensOuServices extends JpaRepository<LigneContrepartieNonMonetairePourBiensOuServicesBD,Long>{

}
