package com.PrixDeTransfert.Backend.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com.PrixDeTransfert.Backend.models.InformationsRemunerationsBiensCorporelsIncorporelsBD;



public interface InterfaceRepositoryInformationsRemunerationsBiens extends JpaRepository<InformationsRemunerationsBiensCorporelsIncorporelsBD,Long> {
	InformationsRemunerationsBiensCorporelsIncorporelsBD findInformationsRemunerationsBiensCorporelsIncorporelsBDById(Long id);
}
