package com.PrixDeTransfert.Backend.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import com.PrixDeTransfert.Backend.models.OperationsSansContrepartieOuAvecContrepartieNonMonetaireBD;



public interface InterfaceRepositoryOperationsSansContrepartieOuAvecContrepartieNonMonetaire extends JpaRepository<OperationsSansContrepartieOuAvecContrepartieNonMonetaireBD,Long> {
	OperationsSansContrepartieOuAvecContrepartieNonMonetaireBD findOperationsSansContrepartieOuAvecContrepartieNonMonetaireBDById(Long IdOperationsSansContrepartieOuAvecContrepartieNonMonetaire);
}
