package com.PrixDeTransfert.Backend.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.PrixDeTransfert.Backend.models.InformationsSurContrepartieNonMonetairePourBiensOuServicesBD;
import com.PrixDeTransfert.Backend.models.OperationsSansContrepartieOuAvecContrepartieNonMonetaireBD;

@Service
public class ServiceInformationsSurContrepartieNonMonetairePourBiensOuServices {
	@Autowired
	com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryInformationsSurContrepartieNonMonetairePourBiensOuServices InterfaceRepositoryInformationsSurContrepartieNonMonetairePourBiensOuServices;
	@Autowired
	com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryOperationsSansContrepartieOuAvecContrepartieNonMonetaire InterfaceRepositoryOperationsSansContrepartieOuAvecContrepartieNonMonetaire;
	
	public InformationsSurContrepartieNonMonetairePourBiensOuServicesBD save(InformationsSurContrepartieNonMonetairePourBiensOuServicesBD a ,Long idOperationsSansContrepartie) {
		OperationsSansContrepartieOuAvecContrepartieNonMonetaireBD OperationsSansContrepartieOuAvecContrepartieNonMonetaire=InterfaceRepositoryOperationsSansContrepartieOuAvecContrepartieNonMonetaire.findOperationsSansContrepartieOuAvecContrepartieNonMonetaireBDById(idOperationsSansContrepartie);
	a.setOperationsSansContrepartieOuAvecContrepartieNonMonetaire(OperationsSansContrepartieOuAvecContrepartieNonMonetaire);
	return InterfaceRepositoryInformationsSurContrepartieNonMonetairePourBiensOuServices.save(a);
	
	
	
	}
}
