package com.PrixDeTransfert.Backend.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.PrixDeTransfert.Backend.models.InformationsSurContrepartieNonMonetairePourBiensOuServicesBD;
import com.PrixDeTransfert.Backend.models.LigneContrepartieNonMonetairePourBiensOuServicesBD;

@Service
public class ServiceLigneContrepartieNonMonetairePourBiensOuServices {
	
	@Autowired
	com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryLigneContrepartieNonMonetairePourBiensOuServices InterfaceRepositoryLigneContrepartieNonMonetairePourBiensOuServices;
	 @Autowired
	 com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryInformationsSurContrepartieNonMonetairePourBiensOuServices InterfaceRepositoryInformationsSurContrepartieNonMonetairePourBiensOuServices ;
	 public LigneContrepartieNonMonetairePourBiensOuServicesBD save(LigneContrepartieNonMonetairePourBiensOuServicesBD a , Long IdInformationsSurContrepartieNonMonetairePourBiensOuServices ) {
		 InformationsSurContrepartieNonMonetairePourBiensOuServicesBD InformationsSurContrepartieNonMonetairePourBiensOuServices=InterfaceRepositoryInformationsSurContrepartieNonMonetairePourBiensOuServices.findInformationsSurContrepartieNonMonetairePourBiensOuServicesBDById(IdInformationsSurContrepartieNonMonetairePourBiensOuServices);
	 a.setInformationsSurContrepartieNonMonetairePourBiensOuServices(InformationsSurContrepartieNonMonetairePourBiensOuServices);
	 return InterfaceRepositoryLigneContrepartieNonMonetairePourBiensOuServices.save(a);
	}

}
