package com.PrixDeTransfert.Backend.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.PrixDeTransfert.Backend.models.InformationsOperationsAccordsPrealablesOuRescritsFiscauxBD;
import com.PrixDeTransfert.Backend.models.LigneOperationsAccordsPrealablesOuRescritsFiscauxBD;
import com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryLigneOperationsAccordsPrealablesOuRescritsFiscaux;

@Service
public class ServiceLigneOperationsAccordsPrealablesOuRescritsFiscaux {
	@Autowired
	InterfaceRepositoryLigneOperationsAccordsPrealablesOuRescritsFiscaux LigneOperationsAccordsPrealablesOuRescritsFiscaux;
	@Autowired
	com.PrixDeTransfert.Backend.repositories.InterfaceRepositoryInformationsOperationsAccordsPrealablesOuRescritsFiscaux InterfaceRepositoryInformationsOperationsAccordsPrealablesOuRescritsFiscaux ;
	
	public LigneOperationsAccordsPrealablesOuRescritsFiscauxBD save(LigneOperationsAccordsPrealablesOuRescritsFiscauxBD a ,Long idLigneOperationsAccordsPrealablesOuRescritsFiscaux) {
		InformationsOperationsAccordsPrealablesOuRescritsFiscauxBD InformationsOperationsAccordsPrealablesOuRescritsFiscaux=InterfaceRepositoryInformationsOperationsAccordsPrealablesOuRescritsFiscaux.findInformationsOperationsAccordsPrealablesOuRescritsFiscauxBDById(idLigneOperationsAccordsPrealablesOuRescritsFiscaux);
		a.setInformationsOperationsAccordsPrealablesOuRescritsFiscaux(InformationsOperationsAccordsPrealablesOuRescritsFiscaux);
		return LigneOperationsAccordsPrealablesOuRescritsFiscaux.save(a);
	}
}
